# Generated by Django 2.0 on 2018-02-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produto',
        ),
    ]
