# Generated by Django 2.0 on 2018-02-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20180212_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='habilidatado',
            new_name='habilitado',
        ),
    ]
