# Generated by Django 2.0 on 2018-02-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20180212_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='desceicao',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
