"""
Django settings for flobike project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import dj_database_url

ALLOWED_HOSTS = ['127.0.0.1', '.herokuapp.com']

#CARREGAR_SESSION_ID = 'carrega'

CART_SESSION_ID = 'cart'



#configurações pro Heroku
#if os.getcwd() == '/app:
if os.getcwd():
    import dj_database_url
    DATABASES = {
		'default':dj_database_url.config(default='postgres://localhost')
	}

#Honra o Cabeçalho 'X-Forwarded-proto' para request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWAEDED_PROTO','https')

#Cabeçalho para Permitir todos os host
ALLOWED_HOSTS = ['*']

#Configurações de recursos estáticos
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = 'staticfiles'
STATIC_DIRS =(
	os.path.join(BASE_DIR,'static')
)



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8#j8p@6cflv_^b=@gf=x*fzlis%t^rt2n*e_cdm(as_txclb0d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# django-paypal settings
PAYPAL_RECEIVER_EMAIL = 'Seu email  pay pal'
#PAYPAL_RECEIVER_PASSWORD='sua senha pay pal'
PAYPAL_TEST = True
# Application definition

INSTALLED_APPS = [
    'paypal.standard.ipn',
    'payment.apps.PaymentConfig',
    'loja.apps.LojaConfig',
    'orders.apps.OrdersConfig',
    'inscrever.apps.InscreverConfig',
    'cart.apps.CartConfig',
    'app.apps.AppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CLOUDINARY = {
    'cloud_name' : 'dmk21ttn3',
    'api_key' : '674443318556841',
    'api_secret': 'KD03NxKL3oFX8KJsyVQ2TaXuH4s'
}

ROOT_URLCONF = 'flobike.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flobike.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
"""" Adicona o upload media= o static"""
MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(PROJECT_ROOT_PATH, 'media')
""" upload caminho onde vão todas as imagens """
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload')
#tem que ir na url padrão adiocionar os statics, MEDIA_URL
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
#Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAUL_FROM_EMAIL='Nome<eltoni.guimaraes@gmail.com>'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'eltoni.guimaraes@gmail.com'
EMAIL_HOST_PASSWORD = '12345qwe'
EMAIL_PORT = 587


CONTACT_EMAIL = 'eltoni.guimaraes@gmail.com'
