# Generated by Django 2.0 on 2018-01-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_final', models.DateTimeField()),
            ],
        ),
    ]
