# Generated by Django 2.0 on 2018-01-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='imagem',
            field=models.ImageField(default=1, upload_to='app/static/imgs/carousel'),
            preserve_default=False,
        ),
    ]
