# Generated by Django 2.0 on 2018-01-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carousel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='imagem',
            field=models.ImageField(upload_to='media/imgs'),
        ),
    ]
