# Generated by Django 2.0 on 2018-01-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180129_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
