# Generated by Django 2.0 on 2018-01-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_topico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_final', models.DateTimeField()),
            ],
        ),
    ]
