# Generated by Django 2.0 on 2018-01-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_patrocinador_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinador',
            name='tipo',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
