# Generated by Django 2.0 on 2018-02-12 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180131_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patrocinador',
        ),
    ]
