# Generated by Django 2.0 on 2018-02-22 23:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_patrocinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
