# Generated by Django 2.0 on 2018-02-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=20)),
                ('ciadade', models.CharField(max_length=100)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-criado',),
            },
        ),
    ]
