# Generated by Django 2.0 on 2018-02-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrever', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrever',
            name='numero',
        ),
        migrations.AlterField(
            model_name='inscrever',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='inscrever',
            name='endereco',
            field=models.CharField(max_length=250, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='inscrever',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Seu Nome'),
        ),
    ]
