# Generated by Django 2.0 on 2018-02-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrever', '0002_auto_20180212_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrever',
            name='ciadade',
        ),
        migrations.AddField(
            model_name='inscrever',
            name='cidade',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
